<craft name="button2">
	<parameter name="radius" type="float" default="2"/>
	<parameter name="ringThickness" type="float"/>
	<parameter name="numberOfHoles" type="int" default="4"/>
	<parameter name="holeSize" type="float" default="0.2"/>
	<parameter name="holeDistance" type="float" default="0.5"/>
	<parameter name="depth" type="float"/>
	<script type="text/openjscad">
	function main(params)
	{
		 //vars
	     var radius = params.radius || 2;
	     if(radius <= 0) radius = 2;
	     
	     var thickness = params.ringThickness || radius/10;
	     if(thickness >= radius) thickness = radius/10;
	     
	     var depth = params.depth || thickness*2;
	     if(depth <= thickness) depth = thickness*2;
	     
	     var holes = params.numberOfHoles || 4;
	     if(holes <= 0) holes = 4;
	     
	     var hole_size = params.holeSize || 0.2;
	     if(hole_size <= 0) hole_size = 0.2;
	     
	     var hole_distance = params.holeDistance || 0.5;
	     if(hole_distance < hole_size) hole_distance = hole_size;
	     //------------------------------
	     
	     var c = cylinder({'r' : radius , 'h' : depth});
	     
	     c = union(c,torus({'ro' : radius - thickness, 'ri' : thickness}).translate([0,0,depth]));
	     c = union(c,
	     			intersection(sphere({'r' : radius - thickness*2}).translate([0,0,depth + thickness*2]).scale([1,1,0.4]),cylinder({'h' : depth + thickness, 'r' : radius - thickness*2}))
	     			);
	     
	     for(var i = 0; i < holes; i++)
	     {
	         c = difference(c, cylinder({'r': hole_size, 'h' : depth*2}).translate([hole_distance*Math.cos(2*Math.PI/holes*i),hole_distance*Math.sin(2*Math.PI/holes*i),-depth + thickness]));
	     }
	     
	     c = difference(c,sphere({'r' : radius - thickness*2}).translate([0,0,depth*10]).scale([1,1,0.15]));
	     
	     return c;
	}

	</script>
</craft>